### ISSUE TITLE
html5 notification VS web push api

### ISSUE THREAD

**Issue by vkhv** [eveness/web-push-api#1]
Что лучше, да и вообще в чем разница между этим html5 notification и web push API?

HTML5 notification не требует регистрации в Google Developer Console?

Что выбрать?

**Comment by vkhv** [comment]
Web notification API in HTML5 is used to display the notifications from a webpage while push API is used to trigger notifications remotely even when the web page is inactive .

**Comment by eveness** [comment]
Сам спросил, сам ответил, сам закрыл :)

Да, верно, отличается принципом работы. Если брать Notifications API, то нужно самому постоянно опрашивать сервер на наличие новых сообщений, либо использовать Web Sockets, если конечно есть такая возможность. Push API использует сервис-воркер, который сам себе тихо ждет, когда к нему придут данные.

Механизм непосредственно отображения уведомлений один и тот же, только в первом случае страница должна быть открыта в браузере (необязательно в активной вкладке насколько помню), во втором необязательно, даже браузер может быть закрыт, если он в фоновом режиме висит.

Можно ещё добавить, что поддержка браузерами у [Notifications API](http://caniuse.com/#feat=notifications) чуть получше.
